### ISSUE TITLE
segmentation fault on wip-tinsimp-greedyinsertion

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#57] opened 2017-12-07 16:39 UTC
@Ylannl I'm trying the `wip-tinsimp-greedyinsertion` branch but I get a segmentation fault at:

```sh
Lifting all input polygons to 3D...
===== /LIFTING =====
===== LIFTING/ =====
=====  /ADJACENT FEATURES =====
=====  ADJACENT FEATURES/ =====
=====  /STITCHING =====
=====  STITCHING/ =====
=====  /BOWTIES =====
=====  BOWTIES/ =====
=====  /VERTICAL WALLS =====
=====  VERTICAL WALLS/ =====
=====  /CDT =====
[1]    25000 segmentation fault  3dfier  -o
```

Here are the files that I used: https://www.dropbox.com/s/6fyuevloj4j0jsx/segfault.zip?dl=0

**Comment by Ylannl** [comment] 2017-12-08 10:23
Thanks for reporting. I can reproduce it on my own machine and I'm looking into it.

**Comment by Ylannl** [comment] 2017-12-10 08:15
The fault was caused by duplicate elevation points (in x,y). I pushed a fix that detects and ignores these duplicates prior to running the greedy insertion algorithm. It shouldn't hurt performance too much.

**Closed** 2017-12-10 08:16 UTC
